"""
Alpata Acoustic Source Localizer -- THE BRAIN
=============================================

You normally do NOT edit this file. All settings live in config.py.

WHAT IT DOES
------------
Every time the server has fresh dB levels from the nodes, you call:

    result = tracker.update({"Alpata-1": 77.1, "Alpata-2": 79.0, ...})

and it returns a smoothed (x, y) point on the room map estimating where the
sound is coming from, plus a confidence flag. Call it continuously and the
point tracks the active speaker.

HOW IT WORKS (the idea)
-----------------------
Louder corner = closer to the sound. We convert each node's dB into a linear
sound-energy weight, place those weights at the node positions from config.py,
and take the weighted-average position. Louder nodes pull the estimate toward
themselves. Then we smooth over time so the point glides instead of twitching.

WHY ENERGY-BASED, NOT TDOA
--------------------------
The nodes are independent WiFi devices with unsynchronised clocks, so true
time-difference-of-arrival is impossible. Energy/loudness needs no sync.
Trade-off: room-zone accuracy (~2-4 m), which is right for steering a camera
but not sub-meter. This is a hardware limit, not a tuning issue.
"""

from __future__ import annotations

from typing import Dict, Optional, Tuple

import config


class AlpataLocalizer:
    """
    Estimates the active-speaker position from per-node dB readings.

    Instantiate once; call update() on every fresh frame from the server.
    All tunable settings come from config.py — do not edit this file.
    """

    def __init__(self) -> None:
        """Load and validate settings from config.py, then initialise state."""
        self._validate_config()

        # Pull everything from the config so this file stays generic.
        self.nodes: Dict[str, Tuple[float, float]] = {
            n["name"]: (n["x"], n["y"]) for n in config.NODES
        }

        profile = config.MIC_PROFILE[config.MIC_TYPE]
        self.noise_floor: float = profile["noise_floor_db"]

        self.contrast: float = config.CONTRAST
        self.smoothing: float = config.SMOOTHING
        self.min_active_db: float = config.MIN_ACTIVE_DB

        self._smoothed: Optional[Tuple[float, float]] = None  # last smoothed (x, y), for continuous tracking

    @staticmethod
    def _validate_config() -> None:
        """
        Check config.py for missing or invalid values before any math runs.

        Raises ValueError with a plain-English message on any problem so the
        next person gets a clear fix rather than a cryptic stack trace.
        """
        required_attrs = ["NODES", "MIC_TYPE", "MIC_PROFILE", "CONTRAST", "SMOOTHING", "MIN_ACTIVE_DB"]
        for attr in required_attrs:
            if not hasattr(config, attr):
                raise ValueError(
                    f"config.py is missing required field '{attr}'. "
                    f"Check that config.py is complete and not accidentally truncated."
                )

        if not isinstance(config.NODES, list) or len(config.NODES) < 3:
            count = len(config.NODES) if isinstance(config.NODES, list) else type(config.NODES).__name__
            raise ValueError(
                f"config.NODES must be a list of at least 3 nodes (got {count!r}). "
                f"Energy-based localisation needs at least 3 reference points to triangulate."
            )

        seen_names: set = set()
        for i, node in enumerate(config.NODES):
            for field in ("name", "x", "y"):
                if field not in node:
                    raise ValueError(
                        f"Node #{i} in config.NODES is missing field '{field}'. "
                        f"Each node must have 'name' (string), 'x' (metres), and 'y' (metres)."
                    )
            name = node["name"]
            if name in seen_names:
                raise ValueError(
                    f"Duplicate node name '{name}' in config.NODES. "
                    f"Each node must have a unique name matching the server's device ID."
                )
            seen_names.add(name)
            for field in ("x", "y"):
                if not isinstance(node[field], (int, float)):
                    raise ValueError(
                        f"Node '{name}' field '{field}' must be a number (metres), "
                        f"got {type(node[field]).__name__!r}. Check your measurements in config.py."
                    )

        if config.MIC_TYPE not in config.MIC_PROFILE:
            known = ", ".join(f"'{k}'" for k in config.MIC_PROFILE)
            raise ValueError(
                f"MIC_TYPE '{config.MIC_TYPE}' is not listed in MIC_PROFILE. "
                f"Known types: {known}. "
                f"Either fix MIC_TYPE or add a new hardware profile to MIC_PROFILE in config.py."
            )

        profile = config.MIC_PROFILE[config.MIC_TYPE]
        if "noise_floor_db" not in profile:
            raise ValueError(
                f"MIC_PROFILE['{config.MIC_TYPE}'] is missing 'noise_floor_db'. "
                f"Add it: measure the idle dB in an empty room and set it a few dB above that."
            )

        for param in ("CONTRAST", "SMOOTHING", "MIN_ACTIVE_DB"):
            val = getattr(config, param)
            if not isinstance(val, (int, float)):
                raise ValueError(
                    f"config.{param} must be a number, got {type(val).__name__!r} ({val!r})."
                )

    @staticmethod
    def _db_to_energy(db: float) -> float:
        """Convert a dB level to a linear energy value (inverse of 10·log10)."""
        return 10.0 ** (db / 10.0)

    def reset(self) -> None:
        """Forget the tracking history (e.g. after a long silence)."""
        self._smoothed = None

    def update(self, readings: Dict[str, float]) -> Optional[Dict]:
        """
        Process one frame of dB readings and return a smoothed position estimate.

        Parameters
        ----------
        readings : dict mapping node name to dB level, e.g. {"Alpata-1": 77.1, ...}.
                   Extra or unknown names are silently ignored; missing nodes are fine.

        Returns
        -------
        dict with keys:
            x, y           -- estimated position in metres (smoothed over time)
            loudest_node   -- name of the node with the highest dB this frame
            spread_db      -- loudest minus quietest dB across active nodes
            confidence     -- "high" (>=8 dB spread), "medium" (>=4), or "low"
        Returns None if the room is quiet or no known nodes are present in readings.

        Raises
        ------
        TypeError  if readings is not a dict.
        ValueError if any dB value in readings is not a number.
        """
        if not isinstance(readings, dict):
            raise TypeError(
                f"update() expects a dict {{node_name: db_value}}, "
                f"got {type(readings).__name__!r}."
            )
        for name, val in readings.items():
            if not isinstance(val, (int, float)):
                raise ValueError(
                    f"dB value for node '{name}' must be a number, "
                    f"got {type(val).__name__!r} ({val!r}). "
                    f"Check the data coming from the server."
                )

        # Keep only nodes we have a known position for.
        valid = {n: db for n, db in readings.items() if n in self.nodes}
        if not valid:
            return None

        loudest_db = max(valid.values())
        if loudest_db < self.min_active_db:
            return None  # nothing loud enough to localize

        # Weight each node by its energy ABOVE the noise floor, then sharpen.
        floor_energy = self._db_to_energy(self.noise_floor)
        weights: Dict[str, float] = {}
        for node, db in valid.items():
            if db <= self.noise_floor:
                weights[node] = 0.0
            else:
                e = self._db_to_energy(db) - floor_energy
                weights[node] = max(e, 0.0) ** self.contrast

        total = sum(weights.values())
        if total <= 0:
            return None

        # Weighted centroid of the node positions = raw estimate.
        x = sum(self.nodes[n][0] * w for n, w in weights.items()) / total
        y = sum(self.nodes[n][1] * w for n, w in weights.items()) / total

        # Temporal smoothing for continuous, non-jittery tracking.
        if self._smoothed is None:
            self._smoothed = (x, y)
        else:
            sx, sy = self._smoothed
            a = self.smoothing
            self._smoothed = (sx + a * (x - sx), sy + a * (y - sy))
        ex, ey = self._smoothed

        # Confidence from the loud/quiet spread.
        spread = loudest_db - min(valid.values())

        return {
            "x": round(ex, 2),
            "y": round(ey, 2),
            "loudest_node": max(valid, key=valid.get),
            "spread_db": round(spread, 1),
            "confidence": ("high" if spread >= 8 else
                           "medium" if spread >= 4 else "low"),
        }
